name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Deploy
        run: |
          # Here you would add your deployment commands
          # For example, deploying to GitHub Pages
          npm install gh-pages --save-dev
          npm run build
          npx gh-pages -d build

